#![allow(unused_imports)]
#![allow(clippy::all)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
#[doc = "The `XrExpression` enum."]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum XrExpression {
    BrowLowererLeft = "brow_lowerer_left",
    BrowLowererRight = "brow_lowerer_right",
    CheekPuffLeft = "cheek_puff_left",
    CheekPuffRight = "cheek_puff_right",
    CheekRaiserLeft = "cheek_raiser_left",
    CheekRaiserRight = "cheek_raiser_right",
    CheekSuckLeft = "cheek_suck_left",
    CheekSuckRight = "cheek_suck_right",
    ChinRaiserBottom = "chin_raiser_bottom",
    ChinRaiserTop = "chin_raiser_top",
    DimplerLeft = "dimpler_left",
    DimplerRight = "dimpler_right",
    EyesClosedLeft = "eyes_closed_left",
    EyesClosedRight = "eyes_closed_right",
    EyesLookDownLeft = "eyes_look_down_left",
    EyesLookDownRight = "eyes_look_down_right",
    EyesLookLeftLeft = "eyes_look_left_left",
    EyesLookLeftRight = "eyes_look_left_right",
    EyesLookRightLeft = "eyes_look_right_left",
    EyesLookRightRight = "eyes_look_right_right",
    EyesLookUpLeft = "eyes_look_up_left",
    EyesLookUpRight = "eyes_look_up_right",
    InnerBrowRaiserLeft = "inner_brow_raiser_left",
    InnerBrowRaiserRight = "inner_brow_raiser_right",
    JawDrop = "jaw_drop",
    JawSidewaysLeft = "jaw_sideways_left",
    JawSidewaysRight = "jaw_sideways_right",
    JawThrust = "jaw_thrust",
    LidTightenerLeft = "lid_tightener_left",
    LidTightenerRight = "lid_tightener_right",
    LipCornerDepressorLeft = "lip_corner_depressor_left",
    LipCornerDepressorRight = "lip_corner_depressor_right",
    LipCornerPullerLeft = "lip_corner_puller_left",
    LipCornerPullerRight = "lip_corner_puller_right",
    LipFunnelerLeftBottom = "lip_funneler_left_bottom",
    LipFunnelerLeftTop = "lip_funneler_left_top",
    LipFunnelerRightBottom = "lip_funneler_right_bottom",
    LipFunnelerRightTop = "lip_funneler_right_top",
    LipPressorLeft = "lip_pressor_left",
    LipPressorRight = "lip_pressor_right",
    LipPuckerLeft = "lip_pucker_left",
    LipPuckerRight = "lip_pucker_right",
    LipStretcherLeft = "lip_stretcher_left",
    LipStretcherRight = "lip_stretcher_right",
    LipSuckLeftBottom = "lip_suck_left_bottom",
    LipSuckLeftTop = "lip_suck_left_top",
    LipSuckRightBottom = "lip_suck_right_bottom",
    LipSuckRightTop = "lip_suck_right_top",
    LipTightenerLeft = "lip_tightener_left",
    LipTightenerRight = "lip_tightener_right",
    LipsToward = "lips_toward",
    LowerLipDepressorLeft = "lower_lip_depressor_left",
    LowerLipDepressorRight = "lower_lip_depressor_right",
    MouthLeft = "mouth_left",
    MouthRight = "mouth_right",
    NoseWrinklerLeft = "nose_wrinkler_left",
    NoseWrinklerRight = "nose_wrinkler_right",
    OuterBrowRaiserLeft = "outer_brow_raiser_left",
    OuterBrowRaiserRight = "outer_brow_raiser_right",
    UpperLidRaiserLeft = "upper_lid_raiser_left",
    UpperLidRaiserRight = "upper_lid_raiser_right",
    UpperLipRaiserLeft = "upper_lip_raiser_left",
    UpperLipRaiserRight = "upper_lip_raiser_right",
}
